-- ══════════════════════════════════════════
--  SmartAgriWeb — Database Schema
-- ══════════════════════════════════════════

-- Users table for authentication
CREATE TABLE IF NOT EXISTS users (
                                     id          INTEGER PRIMARY KEY AUTOINCREMENT,
                                     name        TEXT    NOT NULL,
                                     email       TEXT    NOT NULL UNIQUE,
                                     password    TEXT    NOT NULL,
                                     created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Sensor readings from ESP32 / simulated data
CREATE TABLE IF NOT EXISTS sensor_readings (
                                               id          INTEGER PRIMARY KEY AUTOINCREMENT,
                                               temperature REAL    NOT NULL,
                                               humidity    INTEGER NOT NULL,
                                               soil_moisture INTEGER NOT NULL,
                                               light_lux   REAL    DEFAULT 0,
                                               source      TEXT    DEFAULT 'simulated',  -- 'esp32' or 'simulated'
                                               recorded_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Alerts generated by the alert engine
CREATE TABLE IF NOT EXISTS alerts (
                                      id          INTEGER PRIMARY KEY AUTOINCREMENT,
                                      type        TEXT    NOT NULL,   -- 'warning', 'danger', 'info'
                                      title       TEXT    NOT NULL,
                                      message     TEXT    NOT NULL,
                                      resolved    INTEGER DEFAULT 0,  -- 0=active, 1=resolved
                                      created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Active crops being tracked on this farm
CREATE TABLE IF NOT EXISTS active_crops (
                                            id          INTEGER PRIMARY KEY AUTOINCREMENT,
                                            crop_key    TEXT    NOT NULL,
                                            field_name  TEXT    NOT NULL,
                                            planted_at  DATE    NOT NULL,
                                            status      TEXT    DEFAULT 'growing',  -- 'growing', 'harvested', 'failed'
                                            notes       TEXT    DEFAULT '',
                                            created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Daily irrigation log
CREATE TABLE IF NOT EXISTS irrigation_log (
                                              id          INTEGER PRIMARY KEY AUTOINCREMENT,
                                              liters_used REAL    NOT NULL,
                                              liters_wasted REAL  DEFAULT 0,
                                              crop_key    TEXT,
                                              started_by  TEXT    DEFAULT 'manual',  -- 'manual' or 'auto'
                                              logged_at   TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Seed some initial alerts
INSERT OR IGNORE INTO alerts (id, type, title, message) VALUES
  (1, 'warning', 'Low Water Level',          'Cucumbers tank below 10%'),
  (2, 'danger',  'Over-Irrigation Detected', 'Spinach exceeded daily limit by 25 L');

-- Seed initial sensor readings (last 7 days)
INSERT OR IGNORE INTO sensor_readings (id, temperature, humidity, soil_moisture, recorded_at) VALUES
  (1,  29.0, 58, 58, datetime('now', '-6 days')),
  (2,  31.0, 55, 55, datetime('now', '-5 days')),
  (3,  32.0, 54, 48, datetime('now', '-4 days')),
  (4,  30.0, 56, 50, datetime('now', '-3 days')),
  (5,  31.0, 60, 45, datetime('now', '-2 days')),
  (6,  32.0, 62, 42, datetime('now', '-1 days')),
  (7,  31.0, 60, 43, datetime('now'));

-- Seed irrigation log
INSERT OR IGNORE INTO irrigation_log (id, liters_used, liters_wasted, logged_at) VALUES
  (1, 340, 60, datetime('now', '-6 days')),
  (2, 420, 80, datetime('now', '-5 days')),
  (3, 370, 55, datetime('now', '-4 days')),
  (4, 400, 90, datetime('now', '-3 days')),
  (5, 460,100, datetime('now', '-2 days')),
  (6, 480,110, datetime('now', '-1 days')),
  (7, 520,120, datetime('now'));